title: TacticalNerdery.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  - jekyll-feed
show_content: true
